// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace _2._semesterprojekttest.Models
{
    [Table("Coupon")]
    public partial class Coupon
    {
        [Key]
        [Column("CouponID")]
        public int CouponId { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }
        [Required]
        [Column("info")]
        [StringLength(100)]
        public string Info { get; set; }
        [Required]
        [StringLength(200)]
        public string Barcode { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Driver.Coupons))]
        public virtual Driver User { get; set; }
    }
}