// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace _2._semesterprojekttest.Models
{
    [Table("Driver")]
    public partial class Driver
    {
        [Key]
        [Column("UserID")]
        public int UserId { get; set; }
        [StringLength(50)]
        public string CarType { get; set; }
        [StringLength(50)]
        public string Carcolor { get; set; }
        public int? CouponCount { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(CruizeUser.Driver))]
        public virtual CruizeUser User { get; set; }
    }
}