// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;


#nullable disable

namespace _2._semesterprojekttest.Models
{
    [Table("ImageTest")]
    public partial class ImageTest
    {
        [Key]
        [Column("PictureID")]
        public int PictureId { get; set; }
        [Column("UserID")]
        public int? UserId { get; set; }
        [Column("TypeID")]
        public int? TypeId { get; set; }
        [Column(TypeName = "image")]
        public byte[] Image { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(CruizeUser.ImageTests))]
        public virtual CruizeUser User { get; set; }
    }
}