// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace _2._semesterprojekttest.Models
{
    [Table("Passenger")]
    public partial class Passenger
    {
        [Key]
        [Column("UserID")]
        public int UserId { get; set; }
        [Key]
        [Column("RouteID")]
        public int RouteId { get; set; }

        [ForeignKey(nameof(RouteId))]
        [InverseProperty("Passengers")]
        public virtual Route Route { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(CruizeUser.Passengers))]
        public virtual CruizeUser User { get; set; }
    }
}